name: Build application and deploy

on:
  push:
    branches:
      - master # production branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
          - uses: actions/checkout@v3

          ### 🔍 Add SNYK STEPS HERE ###
          - name: Install Snyk
            uses: snyk/actions/setup@master

          - name: Authenticate Snyk
            run: snyk auth ${{ secrets.SNYK_TOKEN }}

          - name: Snyk Test (Code)
            run: snyk test --severity-threshold=high

          - name: Snyk Test (Docker Image)
            run: |
              docker build -t my-react-app .
              snyk test --docker my-react-app --file=Dockerfile --severity-threshold=high


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t nathmankind/capstone-react-app .

      - name: Publish to Docker hub
        run: docker push nathmankind/capstone-react-app:latest

  deploy:
    needs: build
    runs-on: ec2-latest-v1
    steps:
      - name: -- Pull image from docker hub --
        run: docker pull nathmankind/capstone-react-app:latest

      - name: Delete old container
        run: docker rm -f react-container

      - name: Run docker container
        run: docker run -d -p 3000:80 --name react-container nathmankind/capstone-react-app
